os: linux

language: bash
services: docker

env:
  matrix:
    - VERSION=12
    - VERSION=11
    - VERSION=8

script: bash build_latest.sh $VERSION

stages:
  - linter
  - test

jobs:
  include:
    - stage: linter
      script: ./linter.sh
