name: CI

# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-22.04]
        version: [8, 11, 15, 16]
        vm: [hotspot, openj9]
        package: [jdk, jre]
        runtype: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build - Windows
        if: matrix.os == 'windows-2019' || matrix.os == 'windows-2016'
        run: |
          # add msys2 to the path so the correct exes are used
          $env:PATH="C:\msys64\usr\bin;${env:PATH}"
          C:\msys64\usr\bin\bash -c "./build_latest.sh ${{ matrix.version }} ${{ matrix.vm }} ${{ matrix.package }} ${{ matrix.runtype }}"
        env:
          BUILD_VERSION: ${{ matrix.version }}
          BUILD_OS: ${{ matrix.os }}
          BUILD_VM: ${{ matrix.vm }}
          BUILD_PACKAGE: ${{ matrix.package }}

      - name: Build - Linux
        if: matrix.os == 'ubuntu-22.04'
        run: bash build_latest.sh ${{ matrix.version }} ${{ matrix.vm }} ${{ matrix.package }} ${{ matrix.runtype }}
        env:
          BUILD_VERSION: ${{ matrix.version }}
          BUILD_OS: ${{ matrix.os }}
          BUILD_VM: ${{ matrix.vm }}
          BUILD_PACKAGE: ${{ matrix.package }}
